apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpod01
spec:
  selector:
    matchLabels:
      app: testkube01
  replicas: 3
  template:
    metadata:
      labels:
        app: testkube01
    spec:
      containers:
       - name: podtestkenzo01
         image: httpd
         ports:
         - containerPort: 80