apiVersion: v1
kind: Pod
metadata:
  name: sample-annotations
  annotations:
    annotations: nametest01
    annotations: nametest02
spec:
  containers:
   - name: nginx-container
     image: nginx:1.21.5