apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanechanee01-deployment
spec:
  selector:
    matchLabels:
      app: kanechanee01
  replicas: 1
  template:
    metadata:
      labels:
        app: kanechanee01
    spec:
      containers: 
      - name: kanechanee01
        image: gcr.io/exalted-analogy-209814/hello-app
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: kanechaneetest01-service
spec:
  type: LoadBalancer
  selector:
    app: kanechaneetest01-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
