apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-pods01
spec:
  replicas: 2
  selector:
    matchLabels:
      label1: mysql-01
  template:
    metadata:
      labels:
        label1: mysql-01
    spec:
      containers:
       - name: mysql-container
         image: mysql:latest
         ports:
          - containerPort: 3306
         env:
          - name: MYSQL_ROOT_PASSWORD
            value: P@ssw0rd
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlservice01
spec:
  type: ClusterIP
  ports:
   - port: 3306
  selector:
    label1: mysql-01
